theme: jekyll-theme-primer
<<<<<<< HEAD
remote_theme: gebeto/minimal
=======
# remote_theme: gebeto/minimal
>>>>>>> d5fe201185310979dd6c36f5c164967c926a3c40
logo: https://upload.wikimedia.org/wikipedia/commons/d/de/Nulp_logo_ukr.jpg
google_analytics: UA-120902316-2
google_adsense: 1911696222355014
markdown: kramdown
lang: uk_UA
gems:
  - jekyll-sitemap
