version: '3'
services:
  db:
    build: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/db
    env_file: .env
  server:
    build: server
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./server:/server
      - ./frontend/dist:/server/static
    links:
      - "db:database"
    command: yarn start
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "333:80"
    volumes:
      - "./pgadmin-servers.json:/pgadmin4/servers.json:ro"
      - "./db/storage:/var/lib/pgadmin/storage"
    env_file: .env